export FOX_VIRTUAL_AB_DEVICE=1
export FOX_DELETE_AROMAFM=1
export FOX_USE_BUSYBOX_BINARY=1
export FOX_USE_FSCK_EROFS_BINARY=1
export FOX_VANILLA_BUILD=1

export FOX_ALLOW_EARLY_SETTINGS_LOAD=1
export FOX_SETTINGS_ROOT_DIRECTORY="/data/recovery"

# Extras
export FOX_USE_BASH_SHELL=1
export FOX_USE_NANO_EDITOR=1
export FOX_USE_TAR_BINARY=1
export FOX_USE_SED_BINARY=1
export FOX_USE_XZ_UTILS=1
export FOX_USE_ZSTD_BINARY=1
export FOX_ASH_IS_BASH=1

DIV_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export FOX_LOCAL_CALLBACK_SCRIPT="$DIV_DIR/ramdisk_replace.sh"
 
export ALLOW_MISSING_DEPENDENCIES=true

# Debugging Flags
# export FOX_RESET_SETTINGS=0
# export FOX_INSTALLER_DEBUG_MODE=1
# export OF_DISPLAY_FORMAT_FILESYSTEMS_DEBUG_INFO=1
